
package org.sdss.skyserver;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This is an <b>XML Web Service</b> interface to fetch <b>JPEG</b> image cutouts from the <b>SDSS </b> image archive.<br>Send comments to <b>Maria Nieto-Santisteban</b> -- nieto@pha.jhu.edu
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ImgCutout", targetNamespace = "http://skyserver.sdss.org/", wsdlLocation = "http://casjobs.sdss.org/ImgCutoutDR5/ImgCutout.asmx?wsdl")
public class ImgCutout
    extends Service
{

    private final static URL IMGCUTOUT_WSDL_LOCATION;
    private final static WebServiceException IMGCUTOUT_EXCEPTION;
    private final static QName IMGCUTOUT_QNAME = new QName("http://skyserver.sdss.org/", "ImgCutout");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://casjobs.sdss.org/ImgCutoutDR5/ImgCutout.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMGCUTOUT_WSDL_LOCATION = url;
        IMGCUTOUT_EXCEPTION = e;
    }

    public ImgCutout() {
        super(__getWsdlLocation(), IMGCUTOUT_QNAME);
    }

    public ImgCutout(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMGCUTOUT_QNAME, features);
    }

    public ImgCutout(URL wsdlLocation) {
        super(wsdlLocation, IMGCUTOUT_QNAME);
    }

    public ImgCutout(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMGCUTOUT_QNAME, features);
    }

    public ImgCutout(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImgCutout(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ImgCutoutSoap
     */
    @WebEndpoint(name = "ImgCutoutSoap")
    public ImgCutoutSoap getImgCutoutSoap() {
        return super.getPort(new QName("http://skyserver.sdss.org/", "ImgCutoutSoap"), ImgCutoutSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImgCutoutSoap
     */
    @WebEndpoint(name = "ImgCutoutSoap")
    public ImgCutoutSoap getImgCutoutSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://skyserver.sdss.org/", "ImgCutoutSoap"), ImgCutoutSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMGCUTOUT_EXCEPTION!= null) {
            throw IMGCUTOUT_EXCEPTION;
        }
        return IMGCUTOUT_WSDL_LOCATION;
    }

}
