
package org.sdss.skyserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ImgCutoutSoap", targetNamespace = "http://skyserver.sdss.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ImgCutoutSoap {


    /**
     * Return CVS revision numbers
     * 
     * @return
     *     returns org.sdss.skyserver.ArrayOfString
     */
    @WebMethod(operationName = "Revisions", action = "http://skyserver.sdss.org/Revisions")
    @WebResult(name = "RevisionsResult", targetNamespace = "http://skyserver.sdss.org/")
    @RequestWrapper(localName = "Revisions", targetNamespace = "http://skyserver.sdss.org/", className = "org.sdss.skyserver.Revisions")
    @ResponseWrapper(localName = "RevisionsResponse", targetNamespace = "http://skyserver.sdss.org/", className = "org.sdss.skyserver.RevisionsResponse")
    public ArrayOfString revisions();

    /**
     * Returns the bytes of the Jpeg image for a given pointing<br><b>Input 1:</b> RA in degrees (double)<br><b>Input 2:</b> Dec in degrees (double)<br><b>Input 3:</b> Scale, in arcsec/pixel (double)<br><b>Input 4:</b> Width in pixels (int)<br><b>Input 5:</b> Height in pixels (int)<br><b>Input 6:</b> Drawing options (string)<br><b>Output:</b> Image (byte[])
     * 
     * @param scale
     * @param ra
     * @param height
     * @param dec
     * @param width
     * @param opt
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GetJpeg", action = "http://skyserver.sdss.org/GetJpeg")
    @WebResult(name = "GetJpegResult", targetNamespace = "http://skyserver.sdss.org/")
    @RequestWrapper(localName = "GetJpeg", targetNamespace = "http://skyserver.sdss.org/", className = "org.sdss.skyserver.GetJpeg")
    @ResponseWrapper(localName = "GetJpegResponse", targetNamespace = "http://skyserver.sdss.org/", className = "org.sdss.skyserver.GetJpegResponse")
    public byte[] getJpeg(
        @WebParam(name = "ra_", targetNamespace = "http://skyserver.sdss.org/")
        double ra,
        @WebParam(name = "dec_", targetNamespace = "http://skyserver.sdss.org/")
        double dec,
        @WebParam(name = "scale_", targetNamespace = "http://skyserver.sdss.org/")
        double scale,
        @WebParam(name = "width_", targetNamespace = "http://skyserver.sdss.org/")
        int width,
        @WebParam(name = "height_", targetNamespace = "http://skyserver.sdss.org/")
        int height,
        @WebParam(name = "opt_", targetNamespace = "http://skyserver.sdss.org/")
        String opt);

    /**
     * Returns the bytes of the Jpeg image for a given pointing.<br><b>Input 1:</b> RA in degrees (double)<br><b>Input 2:</b> Dec in degrees (double)<br><b>Input 3:</b> Scale, in arcsec/pixel (double)<br><b>Input 4:</b> Width in pixels (int)<br><b>Input 5:</b> Height in pixels (int)<br><b>Input 6:</b> Drawing options (string)<br><b>Input 7:</B> Marking selection (string)<br>The marking selection string can be:<UL><LI>List of objects. RA and DEC columns must be included. <B>Example:</B><BR><br><TABLE><TR><TD><b>ObjId</b></TD><TD><b>RA</b></TD><TD><b>DEC</b></TD><TD><b>RMag</b></TD></TR><TR><TD>582378008234755083</TD><TD> 195.578582</TD><TD> 2.548192</TD><TD> 23.565</TD></TR><TR><TD> 582378008234754800</TD><TD> 195.572594</TD><TD> 2.554787</TD><TD> 21.446</TD></TR></TABLE><LI>SELECT SQL query. RA and DEC columns must be included. <B>Example:</B><BR><br>'SELECT  top 10 p.objID, p.ra, p.dec, p.r<br>FROM fGetObjFromRect(195.5,195.65,2.5,2.6) n,   PhotoPrimary p<br>WHERE n.objID=p.objID'<LI>String&nbsp;following the pattern: <B><I>ObjType Band (low_mag, high_mag)</I></B><UL><LI><EM><STRONG>ObjType:</STRONG></EM> S | G | P<br>S for Stars<br>G for Galaxies<br>P for both Stars and Galaxies<LI><STRONG><EM>Band:</EM></STRONG>&nbsp;U |&nbsp;G |&nbsp;R | I&nbsp;|&nbsp;Z | A<br>to select objects with <STRONG><EM>Band </EM></STRONG>BETWEEN <STRONG><EM>low_mag</EM></STRONG> AND <STRONG><EM>high_mag</EM></STRONG><P><br>Band 'A' will look for all the objects with values betwen <b><i>low_mag</i></b> and <b><i>high_mag</i></b> 	  for any band (compositions of ORs).<br>Only Stars, Galaxies, or PhotoPrimary objects will be marked when magnitude     ranges are not specified. <B>Examples:</B><BR><br>S<br>S R (0.0, 23.5)<br>G A (10, 25)</P></LI></UL></LI></UL><b>Output:</b> Image (byte[])
     * 
     * @param scale
     * @param ra
     * @param height
     * @param dec
     * @param query
     * @param width
     * @param opt
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GetJpegQuery", action = "http://skyserver.sdss.org/GetJpegQuery")
    @WebResult(name = "GetJpegQueryResult", targetNamespace = "http://skyserver.sdss.org/")
    @RequestWrapper(localName = "GetJpegQuery", targetNamespace = "http://skyserver.sdss.org/", className = "org.sdss.skyserver.GetJpegQuery")
    @ResponseWrapper(localName = "GetJpegQueryResponse", targetNamespace = "http://skyserver.sdss.org/", className = "org.sdss.skyserver.GetJpegQueryResponse")
    public byte[] getJpegQuery(
        @WebParam(name = "ra_", targetNamespace = "http://skyserver.sdss.org/")
        double ra,
        @WebParam(name = "dec_", targetNamespace = "http://skyserver.sdss.org/")
        double dec,
        @WebParam(name = "scale_", targetNamespace = "http://skyserver.sdss.org/")
        double scale,
        @WebParam(name = "width_", targetNamespace = "http://skyserver.sdss.org/")
        int width,
        @WebParam(name = "height_", targetNamespace = "http://skyserver.sdss.org/")
        int height,
        @WebParam(name = "opt_", targetNamespace = "http://skyserver.sdss.org/")
        String opt,
        @WebParam(name = "query_", targetNamespace = "http://skyserver.sdss.org/")
        String query);

    /**
     * Returns the Jpeg image for a given pointing in a SOAP attachment (DIME)<br><b>Input 1:</b> RA in degrees J2000 (double)<br><b>Input 2:</b> Dec in degrees J2000 (double)<br><b>Input 3:</b> Scale, in arcsec/pixel (double)<br><b>Input 4:</b> Width in pixels (int)<br><b>Input 5:</b> Height in pixels (int)<br><b>Input 6:</b> Drawing options (string)<br><b>Output:</b> Jpeg image in attachment
     * 
     * @param scale
     * @param ra
     * @param height
     * @param dec
     * @param width
     * @param opt
     */
    @WebMethod(operationName = "DimeJpeg", action = "http://skyserver.sdss.org/DimeJpeg")
    @RequestWrapper(localName = "DimeJpeg", targetNamespace = "http://skyserver.sdss.org/", className = "org.sdss.skyserver.DimeJpeg")
    @ResponseWrapper(localName = "DimeJpegResponse", targetNamespace = "http://skyserver.sdss.org/", className = "org.sdss.skyserver.DimeJpegResponse")
    public void dimeJpeg(
        @WebParam(name = "ra_", targetNamespace = "http://skyserver.sdss.org/")
        double ra,
        @WebParam(name = "dec_", targetNamespace = "http://skyserver.sdss.org/")
        double dec,
        @WebParam(name = "scale_", targetNamespace = "http://skyserver.sdss.org/")
        double scale,
        @WebParam(name = "width_", targetNamespace = "http://skyserver.sdss.org/")
        int width,
        @WebParam(name = "height_", targetNamespace = "http://skyserver.sdss.org/")
        int height,
        @WebParam(name = "opt_", targetNamespace = "http://skyserver.sdss.org/")
        String opt);

}
